# Generated by Django 4.2.6 on 2023-10-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
