# Generated by Django 4.2.6 on 2023-10-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0005_rename_image_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
