# Generated by Django 4.2.6 on 2023-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential', '0006_rename_img_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
